feat: added footer and main component
blossomlabsio/bloom pull request #10
Opened 2023-10-01 11:35 UTC by A91y

Added footer and main component
Replaced component structure from /components/.../main.tsx ->  /components/.../index.tsx to improve import statements.

2023-10-01 15:16 UTC, ShreyaPrasad1209 commented
@A91y can you add screenshot of how the UI looks like?

2023-10-01 15:32 UTC, ShreyaPrasad1209 requested changes
I've added few review comments, please take a look 👀 
Overall, great improvement from previous PR 😄

2023-10-01 15:32 UTC, ShreyaPrasad1209 commented on src/components/BloomMain/index.tsx
> +export const BloomMain = () => {
can we rename this to LandingPage?

2023-10-01 15:32 UTC, ShreyaPrasad1209 commented on src/components/BloomMain/index.tsx
> +import { BloomComponent } from './styled';
Also rename this to `LandingPageContainer`

2023-10-01 15:32 UTC, ShreyaPrasad1209 commented on src/components/BloomMain/styled.tsx
> +export const BloomComponent = styled.main`
Rename this to LandingPageContainer. Also, awesome for using main and not div 🎉

2023-10-01 15:32 UTC, ShreyaPrasad1209 commented on src/components/BloomMain/styled.tsx
> +  //   box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
please remove this commented code.

2023-10-01 15:32 UTC, ShreyaPrasad1209 commented on src/components/Footer/styled.tsx
> +export const FooterContainer = styled.footer`
good usage of footer element 👏🏻

2023-10-01 15:32 UTC, ShreyaPrasad1209 commented on src/components/NavigationBar/index.tsx
Keep it `main.tsx` only. The main logic of a component sits inside `main.tsx`. Please rename every `index.tsx` to `main.tsx`

2023-10-02 10:23 UTC, A91y commented on src/components/NavigationBar/index.tsx
Resolved in commit [168b6d0](https://github.com/blossomlabsio/bloom/pull/10/commits/168b6d0ba38931639b80a447adc85fbc03f7d74f)

2023-10-02 10:27 UTC, A91y commented on src/components/BloomMain/styled.tsx
> +  //   box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
Resolved in commit [f12579b](https://github.com/blossomlabsio/bloom/pull/10/commits/f12579b1b17efc52a1cd0041a8006c1bab1c96e2)

2023-10-02 10:33 UTC, A91y commented on src/components/BloomMain/index.tsx
> +export const BloomMain = () => {
Resolved in commit [042b677](https://github.com/blossomlabsio/bloom/pull/10/commits/042b6778760b8a976b52cec6be143c25f3c3911c)

2023-10-02 10:34 UTC, A91y commented on src/components/BloomMain/index.tsx
> +import { BloomComponent } from './styled';
Resolved in commit [042b677](https://github.com/blossomlabsio/bloom/pull/10/commits/042b6778760b8a976b52cec6be143c25f3c3911c)

2023-10-02 10:35 UTC, A91y commented
Implemented all the requested changes.

2023-10-02 15:47 UTC, A91y commented
> @A91y can you add screenshot of how the UI looks like?
Here is the Screenshot
<img width="1280" alt="image" src="https://github.com/blossomlabsio/bloom/assets/65825207/3c938961-2b9a-4098-be5e-0f6b612927f3">

2023-10-05 11:34 UTC, ShreyaPrasad1209 approved these changes
LGTM 👍🏻

2023-10-05 11:34 UTC, merged