Create classic login page
blossomlabsio/bloom pull request #20
Opened 2023-10-09 15:09 UTC by ShreyaPrasad1209

This PR is for #14 and contains

- Login page with POST call to /login
- Used `React-router-dom` to route home and login page to different routes
- Error page for invalid routes

2023-10-09 15:15 UTC, ShreyaPrasad1209 commented
@Mr-Sunglasses please review it

2023-10-10 02:25 UTC, Mr-Sunglasses requested changes

2023-10-10 02:25 UTC, Mr-Sunglasses commented on .env
> +REACT_APP_BASE_URL = http://127.0.0.1:8000
Can we change the file name `.env.example` and change the variable `REACT_APP_BASE_URL = ENTER_BACKEND_IP_HERE` so that it's easy for the user to create their env file on there own and adjust it accordingly, as `.env` is ignored by `.gitignore` file

2023-10-10 02:25 UTC, Mr-Sunglasses commented on src/components/LoginPage/main.tsx
> +export const LoginPage = () => {
I have two questions

1. If we are using a form, I think it has an email validator integrated into it, I'm asking this because the backend does not contain any login to validate Email.
2. Same as If we a using a form for password does it contain a password length validator, because the backend does not contain it?

2023-10-10 02:29 UTC, Mr-Sunglasses commented on src/components/LoginPage/main.tsx
> +export const LoginPage = () => {
@ShreyaPrasad1209 LGTM

2023-10-10 02:39 UTC, Mr-Sunglasses approved these changes
LGTM, Awesome work @ShreyaPrasad1209 👏🏻

2023-10-10 02:39 UTC, merged