Improve footer UI
blossomlabsio/bloom pull request #36
Opened 2023-10-13 22:16 UTC by ShreyaPrasad1209

- Used [React Fontawesone](https://fontawesome.com/v5/docs/web/use-with/react) for social media icons
- Used map to refactored Footer code and made it reusable + maintainable

2023-10-13 23:03 UTC, Mr-Sunglasses requested changes
These are the minor changes which can be improved, everything else LGTM 👍🏻

2023-10-13 23:03 UTC, Mr-Sunglasses commented on src/components/Footer/main.tsx
> +          <SocialMediaIcon key={href} href={href}>
We can add a target="_blank" in this component so that, it is open in a new tab, which will enhance the user experience and help's us focus on the main website.

2023-10-14 13:29 UTC, ShreyaPrasad1209 commented on src/components/Footer/main.tsx
> +                <FooterLink href={href}>{name}</FooterLink>
done

2023-10-14 13:29 UTC, ShreyaPrasad1209 commented on src/components/Footer/main.tsx
> +          <SocialMediaIcon key={href} href={href}>
done

2023-10-14 14:50 UTC, merged